#!/bin/sh

set -e
go generate
go get -v

SERVER=root@clrbinetsrv.in2p3.fr
ssh $SERVER -- systemctl stop lpc-srv.service
scp `which lpc-srv` $SERVER:/srv/lpc/.
ssh $SERVER -- systemctl restart lpc-srv.service

